title: University of York Skydiving Club
markdown: kramdown
groundschool-signup: "/404"
mailing-list-signup: "https://forms.gle/vrs1JNoRYocwEBHC7"
tunnel-signup: "https://forms.gle/Dp7HJYuPUyVXnR2dA"
email: "skydiving@yorksu.org"